// <auto-generated />
using System;
using Basta.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Basta.Server.Migrations
{
    [DbContext(typeof(BastaDbContext))]
    [Migration("20260512001535_FixPendingModelChanges")]
    partial class FixPendingModelChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Basta.Server.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpanishName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ValidationType")
                        .HasColumnType("INTEGER");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            EnglishName = "Name",
                            SpanishName = "Nombre",
                            ValidationType = 3
                        },
                        new
                        {
                            CategoryId = 2,
                            EnglishName = "Animal",
                            SpanishName = "Animal",
                            ValidationType = 4
                        },
                        new
                        {
                            CategoryId = 3,
                            EnglishName = "City/Country",
                            SpanishName = "Ciudad/País",
                            ValidationType = 2
                        },
                        new
                        {
                            CategoryId = 4,
                            EnglishName = "Food/Drink",
                            SpanishName = "Comida/Bebida",
                            ValidationType = 0
                        },
                        new
                        {
                            CategoryId = 5,
                            EnglishName = "Color",
                            SpanishName = "Color",
                            ValidationType = 0
                        },
                        new
                        {
                            CategoryId = 6,
                            EnglishName = "Thing",
                            SpanishName = "Cosa",
                            ValidationType = 0
                        },
                        new
                        {
                            CategoryId = 7,
                            EnglishName = "Profession",
                            SpanishName = "Profesión",
                            ValidationType = 0
                        },
                        new
                        {
                            CategoryId = 8,
                            EnglishName = "Brand",
                            SpanishName = "Marca",
                            ValidationType = 0
                        });
                });

            modelBuilder.Entity("Basta.Server.Entities.Game", b =>
                {
                    b.Property<string>("GameId")
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<int>("HostUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TimerDuration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalRounds")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameId");

                    b.HasIndex("HostUserId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Basta.Server.Entities.GamePlayer", b =>
                {
                    b.Property<int>("GamePlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CumulativeScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GamePlayerId");

                    b.HasIndex("UserId");

                    b.HasIndex("GameId", "UserId")
                        .IsUnique();

                    b.ToTable("GamePlayers");
                });

            modelBuilder.Entity("Basta.Server.Entities.RoundAnswer", b =>
                {
                    b.Property<int>("RoundAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("DictionaryValid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsValid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsAwarded")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequiresPeerReview")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubmittedAnswer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoundAnswerId");

                    b.HasIndex("UserId");

                    b.HasIndex("GameId", "RoundNumber", "UserId", "CategoryId")
                        .IsUnique();

                    b.ToTable("RoundAnswers");
                });

            modelBuilder.Entity("Basta.Server.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("en");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Basta.Server.Entities.Game", b =>
                {
                    b.HasOne("Basta.Server.Entities.User", "Host")
                        .WithMany("HostedGames")
                        .HasForeignKey("HostUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Host");
                });

            modelBuilder.Entity("Basta.Server.Entities.GamePlayer", b =>
                {
                    b.HasOne("Basta.Server.Entities.Game", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Basta.Server.Entities.User", "User")
                        .WithMany("Participations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Basta.Server.Entities.RoundAnswer", b =>
                {
                    b.HasOne("Basta.Server.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Basta.Server.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Basta.Server.Entities.Game", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Basta.Server.Entities.User", b =>
                {
                    b.Navigation("HostedGames");

                    b.Navigation("Participations");
                });
#pragma warning restore 612, 618
        }
    }
}
